- job:
    name: ansible-role-gearman-base
    pre-run: tests/playbooks/pre.yaml
    run: tests/playbooks/run.yaml
    post-run: tests/collect-logs.yaml
    roles:
      - zuul: windmill/ansible-role-gear

# Testing for gearman_install_method: pip
- job:
    name: ansible-role-gearman
    parent: ansible-role-gearman-base

- job:
    name: ansible-role-gearman-fedora-latest
    parent: ansible-role-gearman
    nodeset: fedora-latest

- job:
    name: ansible-role-gearman-ubuntu-bionic
    parent: ansible-role-gearman
    nodeset: ubuntu-bionic

# Testing for gearman_install_method: git
- job:
    name: ansible-role-gearman-src
    parent: ansible-role-gearman-base
    required-projects:
      - name: opendev/gear
    vars:
      gear_git_update: false
      gear_install_method: git

- job:
    name: ansible-role-gearman-src-fedora-latest
    parent: ansible-role-gearman-src
    nodeset: fedora-latest

- job:
    name: ansible-role-gearman-src-ubuntu-bionic
    parent: ansible-role-gearman-src
    nodeset: ubuntu-bionic

- project:
    templates:
      - windmill-jobs-fedora-latest
      - windmill-jobs-bionic
    check:
      jobs:
        - ansible-role-gearman-fedora-latest
        - ansible-role-gearman-ubuntu-bionic
        - ansible-role-gearman-src-fedora-latest
        - ansible-role-gearman-src-ubuntu-bionic
        - tox-linters
    gate:
      jobs:
        - ansible-role-gearman-fedora-latest
        - ansible-role-gearman-ubuntu-bionic
        - ansible-role-gearman-src-fedora-latest
        - ansible-role-gearman-src-ubuntu-bionic
        - tox-linters
